"""PRD §8.1 고정 문자열·코드 — 패키지 `magic_square.constants`와 동일 원천."""

from magic_square.constants import (
    CELL_BLANK,
    CODE_BLANK_COUNT_INVALID,
    CODE_DUPLICATE_NONZERO,
    CODE_INTERNAL_ERROR,
    CODE_NOT_MAGIC_SQUARE,
    CODE_SIZE_INVALID,
    CODE_VALUE_OUT_OF_RANGE,
    DOMAIN_NOT_MAGIC_CODE,
    MAGIC_SUM,
    MATRIX_SIZE,
    MSG_BLANK_COUNT_INVALID,
    MSG_DUPLICATE_NONZERO,
    MSG_INTERNAL_ERROR,
    MSG_NOT_MAGIC_SQUARE,
    MSG_SIZE_INVALID,
    MSG_VALUE_OUT_OF_RANGE,
    VALUE_MAX,
    VALUE_MIN,
)

GRID_SIZE = MATRIX_SIZE
